---
apiVersion: v1
kind: Service
metadata:
  name: lunch-api
  annotations:
    traefik.backend.circuitbreaker: "NetworkErrorRatio() > 0.5"
spec:
  ports:
  - name: http
    targetPort: 5000
    port: 80
  selector:
    app: evry-lunch-api
    version: v1
